name: Deployment SendEmail App

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: 18
            -   name: Install dependecies
                run: npm install
            -   name: Build app
                run: npm run build
            -   name: Deploy to Github Pages
                uses: crazy-max/ghaction-github-pages@v4
                with:
                    target_branch: gh-pages
                    build_dir: build
                    author: LUIGIWONKA
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
